- name: Configure qbittorrent
  import_tasks: qbittorrent.yml
  tags:
    - arr
    - arr-qbittorrent

- name: Deplay arr docker stack
  import_tasks: docker.yml
  tags:
    - arr
    - arr-docker

- name: Configure Prowlarr
  import_tasks: prowlarr.yml
  tags:
    - arr
    - arr-prowlarr

- name: Configure Lidarr
  import_tasks: lidarr.yml
  tags:
    - arr
    - arr-lidarr

- name: Configure Sonarr
  import_tasks: sonarr.yml
  tags:
    - arr
    - arr-sonarr

