$ANSIBLE_VAULT;1.1;AES256
38613964343437326434353735626237653562343635376237636538343530383037343463393664
6535313561343135333337316664353139373532316637630a363163313631666239666530343462
33336664366134343530663331323330636462393164343630386136383933636633393932626564
3636363834343632320a376437626538336431336436636339326636386463623336313261323561
63626265323635383361626638643239373031316534636164336437626166303862613234303030
63366662353836666431636634613662326632343338626234623330373866653237303839303831
39396363626366643631323033366565613136663161393230303661303061646463373435623234
65623436393434343464353263626538323633663661633735646231643963363834633930663765
63336430376430316366663763333933373535303662373362343535663434346138373365366466
33636137643735613061663865343730666664333933636361636662353264613265346461306432
61666166323034653332646237383632386335376561306237626163626564343237376463386136
39393337613363626462616136356638616339643962313864653166613130316439666234646436
63373365393562386638383333323364376236623831366531316537616565306330376430666662
6364323638666435623138636663626361666363343130333730
