- hosts: regensburg
  become: true
  roles:    
    - tailscale
    - base
    - storage
    - geerlingguy.docker
    - docker
    - arr
# TODO: reverse putting all arrs behind vpn but make a docker network for them